language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: TD5Grv+Seo9DPZ3dD9cFW5UYjtnulKB72MGwrdX+FCWipAGcBwTQ5JcDuT0cvqm7cc9U5VM3UUdX7Al5Z8uYWRCKih15hDd8iOBcqg6XEHgaNPCcM+Vwx87mQV1Gb0jqJkMrA29fNJ60v2p7BUKwqO+djzjJNyC3aIzCakCCSS5JTmqavNmXG72G3BB/gKnDAL/RKXcUGqu+jBg8+tsW+konyduyL50hu6g1CjZKcV4fi4qETIiwEV931UQMk1Zrl0m2kWDIG3gEgVd2JF7AkExxvFZg8Z+UZ3hLsQ7arEEhMObtaQek387M1AYNVHURrDqAyHQwODJucYx9YkAZfDNlfy9MiNF7nAv/PqZFZRqHWRO2W9ryyIsx+/lowSocSkCHhmeovj0U+S8FZzK+EwZM6Ji7Z5u36pm8xwUYUSAVnuEtV+lcmA0hssD0sh5rH+lJbKO4ZFsiFHvR7W3hTHO7ryh7vOfswin0v5OGgmgGwC24QN0D/aBmNxifUXnE5lLAQEYTD8PH/fcG//jDDNuWgIOKTTuLWfPJ7VBxHYiOcoz+V0Avq/H3/4rn2O7D6CAXD34otbBgjt9xE1kuotyVcnlZ8VqVv32Sscg0M/kdJxcoYGhrGnJ675l5pNXj8XFBqwZdsUIbSCC2OqWovK/zBY/0Kw3RJZ8gvhUeRz0=
  - secure: xSwAgcnCnBdAsTIgD8gyfkC7g1NejY8U+LlCGC+BSrP2ppPirFvwaJJtDZqdGOzZYJbHbBXuCyG4hDpIep3AWF0xII5Sdo3B4gmnlMjfmFcdlAmGPE6V2Ceh2R+Myp0WXeFbzuX1qF1GGCjAXHiuxDISJMniWMOOlULoNESmWexR9Rwbm+8HU9ek8Hljog6cQpU8KDC2lo5fZE2tB0N0vphiykp+q/PZfBewYYCqlf4ycsfOeNhn7II1HxCg5f0LJYJHXd5e8YUmyroi5ZRKwueNCn0dhqKhkoPrVRUw09Uc6sPuFDCd9rw2qwHDY1x7Rc99v0A61Ea4hF0H5Ee8B74uuVW+CqkKjecCIWhbLwzSY8Q7E2kXMgqUdmSmjJEjXVzR75CjZBAhZeOU/zJSjrdn9VKn2sxnTOOg5Q4OnLpoXnLGJzjxrgIKKYVfUT5Wr1OU8mTRRjkjof2UHxdtUtyAJ8R6kNlDgTitsXq6/XIoz1gFpmVPHRL3TXiS7O7mZ9qWM3uAppddzLXwleiRJmBiZcnXUENT1gAPwqTAAwYwXXIrbnE0ixp9ZkKCaG6ewsq81ZEsk/G+PzOTNN5Sbj+2mHuQEcaZOWbZDsjfGDiWb0CKrtS1vol2XQCmnzaOjx1tXgnp+0Hvg9tB/7pcKgaluiXqXv/5VfDsdkVrnFQ=
  - secure: BPd2vbzCriCiZofCM6m2vQlRBJTuVktZMEPYEXNU6sWnYNQroTBDkvDIT4WzBeLiG5KtUEF9T27HANhL5xWowhExqXZZu6CZNqliWIcLI+xuh30d3dxEammyhiHo2xA3uD9p5S+LLt8doDDkwpcedLNWgK2HGAEo4KhghmeGuiy0ePXa6J80jft9/dLWR0Oyfl1RpIwKcfgftxZ9ud5xSM+YoWPyjMmg6kyU7OvC360ilNyHo7BD0XaInwi2qgbOh23yGPYYThc2Ww8900Iopd+UWuxX7ddIZHXLrrg5EuBhpxeJNGJHo6Nen31siHNzW3k7EnekxDuZrrehAZNcHHt7FduFkUb/a3MRLof2Ogc0nzGV1dE/Emy3nHKl+jP+H2IEn4Shr0fffcjISTtwoyE5FfiYBKkMY63wuF1BR/M+hWkbHX94sCh2U41rybedTLjb6MfqRdWtXoll79906cpfZzaOIWxv7fFW27/4iFSmvpkhEBWGFnv7uUemcjEVvbIbBGHaqAwk10RLRwbqmLLOtjJxY0KBgF17l0IusWd3FNSMcSXSNbT9YnUMsvOwWErtMqEu6ZvaqvUoQbAUrS3/sVfYsHZ9Bgz5KGsd57itAOHq1lhVCGPHbLSnWslst3v4cF9lX1A0uicffq1WAt/Qb5JRBsYnGag5kEboPXk=

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
